"""
Bundled chemical data for ~35 common paint and coating chemicals.

This data is hardcoded from verified public sources (NIOSH Pocket Guide,
OSHA, ECHA, DOT 49 CFR). It loads instantly with no internet access and
no downloads required.

Run:  python3 db_update.py --source bundled
  or: python3 db_update.py   (bundled is always loaded first)
"""

import json
import os
import sqlite3
from datetime import datetime, timezone

# ── Chemical data ─────────────────────────────────────────────────────────────
# Fields: cas, name, synonyms, formula, mw, bp, mp, fp, auto_ign, density,
#         solubility, vapor_pressure, ghs_us_h, ghs_eu_h, signal, p_codes,
#         osha_pel, niosh_rel, niosh_idlh, acgih_tlv,
#         un, dot_class, dot_pg, dot_labels, marine

CHEMICALS = [
    # ── Solvents ──────────────────────────────────────────────────────────────
    {
        'cas': '67-64-1', 'name': 'Acetone',
        'synonyms': ['Propan-2-one', '2-Propanone', 'Dimethyl ketone', 'DMK'],
        'formula': 'C3H6O', 'mw': 58.08,
        'bp': '56 °C (133 °F)', 'mp': '-95 °C', 'fp': '-20 °C (-4 °F)',
        'auto_ign': '465 °C', 'density': '0.79 g/cm³',
        'solubility': 'Miscible with water', 'vapor_pressure': '231 mmHg at 20°C',
        'ghs_us_h': ['H225', 'H319', 'H336'], 'ghs_eu_h': ['H225', 'H319', 'H336'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P233', 'P240', 'P241', 'P242', 'P243', 'P264', 'P271',
                    'P280', 'P303+P361+P353', 'P304+P340', 'P305+P351+P338',
                    'P312', 'P337+P313', 'P370+P378', 'P403+P235', 'P501'],
        'osha_pel': '1000 ppm (2400 mg/m³) TWA', 'niosh_rel': '250 ppm (590 mg/m³) TWA',
        'niosh_idlh': '2500 ppm', 'acgih_tlv': '500 ppm TWA; 750 ppm STEL',
        'un': 'UN1090', 'dot_class': '3', 'dot_pg': 'II',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '64-17-5', 'name': 'Ethanol',
        'synonyms': ['Ethyl alcohol', 'Grain alcohol', 'Alcohol', 'EtOH'],
        'formula': 'C2H6O', 'mw': 46.07,
        'bp': '78 °C (172 °F)', 'mp': '-114 °C', 'fp': '13 °C (55 °F)',
        'auto_ign': '365 °C', 'density': '0.789 g/cm³',
        'solubility': 'Miscible with water', 'vapor_pressure': '59 mmHg at 20°C',
        'ghs_us_h': ['H225', 'H319'], 'ghs_eu_h': ['H225', 'H319'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P233', 'P240', 'P241', 'P242', 'P243', 'P264', 'P280',
                    'P303+P361+P353', 'P305+P351+P338', 'P337+P313', 'P370+P378',
                    'P403+P235', 'P501'],
        'osha_pel': '1000 ppm (1900 mg/m³) TWA', 'niosh_rel': '1000 ppm (1900 mg/m³) TWA',
        'niosh_idlh': '3300 ppm', 'acgih_tlv': '1000 ppm TWA',
        'un': 'UN1170', 'dot_class': '3', 'dot_pg': 'II',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '67-63-0', 'name': 'Isopropanol',
        'synonyms': ['Isopropyl alcohol', '2-Propanol', 'IPA', 'Rubbing alcohol'],
        'formula': 'C3H8O', 'mw': 60.10,
        'bp': '82 °C (180 °F)', 'mp': '-89 °C', 'fp': '12 °C (53 °F)',
        'auto_ign': '399 °C', 'density': '0.786 g/cm³',
        'solubility': 'Miscible with water', 'vapor_pressure': '33 mmHg at 20°C',
        'ghs_us_h': ['H225', 'H319', 'H336'], 'ghs_eu_h': ['H225', 'H319', 'H336'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P233', 'P240', 'P241', 'P242', 'P243', 'P260', 'P264',
                    'P271', 'P280', 'P303+P361+P353', 'P304+P340', 'P305+P351+P338',
                    'P312', 'P337+P313', 'P370+P378', 'P403+P235', 'P501'],
        'osha_pel': '400 ppm (980 mg/m³) TWA', 'niosh_rel': '400 ppm (980 mg/m³) TWA',
        'niosh_idlh': '2000 ppm', 'acgih_tlv': '200 ppm TWA; 400 ppm STEL',
        'un': 'UN1219', 'dot_class': '3', 'dot_pg': 'II',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '108-88-3', 'name': 'Toluene',
        'synonyms': ['Methylbenzene', 'Toluol', 'Phenylmethane'],
        'formula': 'C7H8', 'mw': 92.14,
        'bp': '111 °C (232 °F)', 'mp': '-93 °C', 'fp': '4 °C (39 °F)',
        'auto_ign': '480 °C', 'density': '0.867 g/cm³',
        'solubility': '526 mg/L at 20°C', 'vapor_pressure': '29 mmHg at 20°C',
        'ghs_us_h': ['H225', 'H304', 'H315', 'H336', 'H361d', 'H373'],
        'ghs_eu_h': ['H225', 'H304', 'H315', 'H336', 'H361d', 'H373'],
        'signal': 'Danger',
        'p_codes': ['P201', 'P202', 'P210', 'P260', 'P264', 'P270', 'P271', 'P280',
                    'P301+P310', 'P303+P361+P353', 'P304+P340', 'P308+P313',
                    'P312', 'P314', 'P331', 'P370+P378', 'P403+P235', 'P405', 'P501'],
        'osha_pel': '200 ppm (750 mg/m³) TWA; 300 ppm ceiling',
        'niosh_rel': '100 ppm (375 mg/m³) TWA; 150 ppm STEL',
        'niosh_idlh': '500 ppm', 'acgih_tlv': '20 ppm TWA',
        'un': 'UN1294', 'dot_class': '3', 'dot_pg': 'II',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '1330-20-7', 'name': 'Xylene',
        'synonyms': ['Dimethylbenzene', 'Xylol', 'Mixed xylenes'],
        'formula': 'C8H10', 'mw': 106.17,
        'bp': '138-144 °C (280-291 °F)', 'mp': '-47 °C', 'fp': '27 °C (81 °F)',
        'auto_ign': '463 °C', 'density': '0.864 g/cm³',
        'solubility': '175 mg/L at 25°C', 'vapor_pressure': '9 mmHg at 20°C',
        'ghs_us_h': ['H226', 'H312', 'H315', 'H332', 'H335', 'H336'],
        'ghs_eu_h': ['H226', 'H312', 'H315', 'H332', 'H335', 'H336'],
        'signal': 'Warning',
        'p_codes': ['P210', 'P233', 'P260', 'P271', 'P272', 'P273', 'P280',
                    'P302+P352', 'P303+P361+P353', 'P304+P340', 'P312', 'P321',
                    'P330', 'P362+P364', 'P370+P378', 'P403+P235', 'P501'],
        'osha_pel': '100 ppm (435 mg/m³) TWA',
        'niosh_rel': '100 ppm (435 mg/m³) TWA; 150 ppm STEL',
        'niosh_idlh': '900 ppm', 'acgih_tlv': '100 ppm TWA; 150 ppm STEL',
        'un': 'UN1307', 'dot_class': '3', 'dot_pg': 'III',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '8052-41-3', 'name': 'Mineral spirits',
        'synonyms': ['Stoddard solvent', 'White spirits', 'Petroleum spirits', 'Naphtha'],
        'formula': '', 'mw': None,
        'bp': '149-204 °C (300-400 °F)', 'mp': None, 'fp': '38-61 °C (100-142 °F)',
        'auto_ign': '260 °C', 'density': '0.77 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<2 mmHg at 20°C',
        'ghs_us_h': ['H226', 'H304', 'H336', 'H411'],
        'ghs_eu_h': ['H226', 'H304', 'H336', 'H411'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P261', 'P271', 'P273', 'P280', 'P301+P330+P331',
                    'P303+P361+P353', 'P304+P340', 'P331', 'P370+P378',
                    'P391', 'P403+P235', 'P405', 'P501'],
        'osha_pel': '500 ppm (2900 mg/m³) TWA',
        'niosh_rel': '350 mg/m³ TWA; 1800 mg/m³ ceiling (15 min)',
        'niosh_idlh': '20000 mg/m³', 'acgih_tlv': '100 ppm TWA (as total HC vapor)',
        'un': 'UN1300', 'dot_class': '3', 'dot_pg': 'III',
        'dot_labels': 'Flammable Liquid', 'marine': True,
    },
    {
        'cas': '78-93-3', 'name': 'Methyl ethyl ketone',
        'synonyms': ['MEK', '2-Butanone', 'Butanone', 'Ethyl methyl ketone'],
        'formula': 'C4H8O', 'mw': 72.11,
        'bp': '79.6 °C (175 °F)', 'mp': '-86 °C', 'fp': '-9 °C (16 °F)',
        'auto_ign': '404 °C', 'density': '0.805 g/cm³',
        'solubility': '275 g/L at 20°C', 'vapor_pressure': '78 mmHg at 20°C',
        'ghs_us_h': ['H225', 'H319', 'H336'], 'ghs_eu_h': ['H225', 'H319', 'H336'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P233', 'P240', 'P241', 'P242', 'P243', 'P260', 'P264',
                    'P271', 'P280', 'P303+P361+P353', 'P304+P340', 'P305+P351+P338',
                    'P312', 'P337+P313', 'P370+P378', 'P403+P235', 'P501'],
        'osha_pel': '200 ppm (590 mg/m³) TWA', 'niosh_rel': '200 ppm (590 mg/m³) TWA',
        'niosh_idlh': '3000 ppm', 'acgih_tlv': '200 ppm TWA; 300 ppm STEL',
        'un': 'UN1193', 'dot_class': '3', 'dot_pg': 'II',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '141-78-6', 'name': 'Ethyl acetate',
        'synonyms': ['Acetic acid ethyl ester', 'Ethyl ethanoate', 'EtOAc'],
        'formula': 'C4H8O2', 'mw': 88.11,
        'bp': '77 °C (171 °F)', 'mp': '-84 °C', 'fp': '-4 °C (25 °F)',
        'auto_ign': '426 °C', 'density': '0.902 g/cm³',
        'solubility': '80 g/L at 20°C', 'vapor_pressure': '73 mmHg at 20°C',
        'ghs_us_h': ['H225', 'H319', 'H336'], 'ghs_eu_h': ['H225', 'H319', 'H336'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P233', 'P240', 'P241', 'P242', 'P243', 'P264', 'P271',
                    'P280', 'P303+P361+P353', 'P304+P340', 'P305+P351+P338',
                    'P312', 'P337+P313', 'P370+P378', 'P403+P235', 'P501'],
        'osha_pel': '400 ppm (1400 mg/m³) TWA', 'niosh_rel': '400 ppm (1400 mg/m³) TWA',
        'niosh_idlh': '2000 ppm', 'acgih_tlv': '400 ppm TWA',
        'un': 'UN1173', 'dot_class': '3', 'dot_pg': 'II',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '71-36-3', 'name': 'n-Butanol',
        'synonyms': ['1-Butanol', 'Butyl alcohol', 'n-Butyl alcohol', 'NBA'],
        'formula': 'C4H10O', 'mw': 74.12,
        'bp': '118 °C (244 °F)', 'mp': '-89 °C', 'fp': '29 °C (84 °F)',
        'auto_ign': '343 °C', 'density': '0.810 g/cm³',
        'solubility': '73 g/L at 20°C', 'vapor_pressure': '6.7 mmHg at 20°C',
        'ghs_us_h': ['H226', 'H302', 'H315', 'H318', 'H335', 'H336'],
        'ghs_eu_h': ['H226', 'H302', 'H318', 'H335', 'H336'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P260', 'P264', 'P270', 'P271', 'P280', 'P301+P312',
                    'P303+P361+P353', 'P304+P340', 'P305+P351+P338', 'P310',
                    'P330', 'P370+P378', 'P403+P235', 'P501'],
        'osha_pel': '100 ppm (300 mg/m³) ceiling',
        'niosh_rel': '50 ppm (150 mg/m³) TWA',
        'niosh_idlh': '1400 ppm', 'acgih_tlv': '20 ppm TWA (ceiling)',
        'un': 'UN1120', 'dot_class': '3', 'dot_pg': 'III',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '111-76-2', 'name': '2-Butoxyethanol',
        'synonyms': ['Ethylene glycol monobutyl ether', 'Butyl cellosolve', 'EGBE'],
        'formula': 'C6H14O2', 'mw': 118.17,
        'bp': '171 °C (340 °F)', 'mp': '-77 °C', 'fp': '60 °C (140 °F)',
        'auto_ign': '238 °C', 'density': '0.902 g/cm³',
        'solubility': 'Miscible with water', 'vapor_pressure': '0.88 mmHg at 20°C',
        'ghs_us_h': ['H302', 'H312', 'H332'], 'ghs_eu_h': ['H302', 'H312', 'H332'],
        'signal': 'Warning',
        'p_codes': ['P260', 'P270', 'P271', 'P301+P312', 'P302+P352',
                    'P304+P340', 'P312', 'P330', 'P501'],
        'osha_pel': '50 ppm (240 mg/m³) TWA (skin)',
        'niosh_rel': '5 ppm (24 mg/m³) TWA',
        'niosh_idlh': '700 ppm', 'acgih_tlv': '20 ppm TWA (skin)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '57-55-6', 'name': 'Propylene glycol',
        'synonyms': ['1,2-Propanediol', '1,2-Propylene glycol', 'PG'],
        'formula': 'C3H8O2', 'mw': 76.09,
        'bp': '188 °C (370 °F)', 'mp': '-59 °C', 'fp': '99 °C (210 °F)',
        'auto_ign': '371 °C', 'density': '1.036 g/cm³',
        'solubility': 'Miscible with water', 'vapor_pressure': '0.08 mmHg at 20°C',
        'ghs_us_h': [], 'ghs_eu_h': [], 'signal': None, 'p_codes': [],
        'osha_pel': 'Not established', 'niosh_rel': 'Not established',
        'niosh_idlh': 'Not determined', 'acgih_tlv': '10 mg/m³ TWA (aerosol)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '64742-48-9', 'name': 'Naphtha, hydrotreated light',
        'synonyms': ['VM&P Naphtha', 'Petroleum naphtha', 'Light aliphatic solvent naphtha'],
        'formula': '', 'mw': None,
        'bp': '60-100 °C', 'mp': None, 'fp': '-18 °C (0 °F)',
        'auto_ign': '240 °C', 'density': '0.694 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '>20 mmHg at 20°C',
        'ghs_us_h': ['H225', 'H304', 'H315', 'H336', 'H411'],
        'ghs_eu_h': ['H225', 'H304', 'H315', 'H336', 'H411'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P261', 'P271', 'P273', 'P280', 'P301+P330+P331',
                    'P303+P361+P353', 'P304+P340', 'P331', 'P370+P378',
                    'P391', 'P403+P235', 'P405', 'P501'],
        'osha_pel': '500 ppm TWA', 'niosh_rel': '350 mg/m³ TWA',
        'niosh_idlh': None, 'acgih_tlv': '400 ppm TWA',
        'un': 'UN1268', 'dot_class': '3', 'dot_pg': 'II',
        'dot_labels': 'Flammable Liquid', 'marine': True,
    },
    {
        'cas': '67-56-1', 'name': 'Methanol',
        'synonyms': ['Methyl alcohol', 'Wood alcohol', 'Carbinol', 'MeOH'],
        'formula': 'CH4O', 'mw': 32.04,
        'bp': '64.7 °C (148 °F)', 'mp': '-98 °C', 'fp': '11 °C (52 °F)',
        'auto_ign': '455 °C', 'density': '0.791 g/cm³',
        'solubility': 'Miscible with water', 'vapor_pressure': '97 mmHg at 20°C',
        'ghs_us_h': ['H225', 'H301', 'H311', 'H331', 'H370'],
        'ghs_eu_h': ['H225', 'H301', 'H311', 'H331', 'H370'],
        'signal': 'Danger',
        'p_codes': ['P210', 'P233', 'P240', 'P241', 'P242', 'P243', 'P260', 'P264',
                    'P270', 'P271', 'P280', 'P301+P310', 'P302+P352',
                    'P303+P361+P353', 'P304+P340', 'P307+P311', 'P312',
                    'P330', 'P370+P378', 'P403+P235', 'P405', 'P501'],
        'osha_pel': '200 ppm (260 mg/m³) TWA',
        'niosh_rel': '200 ppm (260 mg/m³) TWA; 250 ppm STEL (skin)',
        'niosh_idlh': '6000 ppm', 'acgih_tlv': '200 ppm TWA; 250 ppm STEL (skin)',
        'un': 'UN1230', 'dot_class': '3', 'dot_pg': 'II',
        'dot_labels': 'Flammable Liquid, Toxic', 'marine': False,
    },
    # ── Pigments ──────────────────────────────────────────────────────────────
    {
        'cas': '13463-67-7', 'name': 'Titanium dioxide',
        'synonyms': ['TiO2', 'Titanium(IV) oxide', 'Titania', 'CI Pigment White 6'],
        'formula': 'TiO2', 'mw': 79.87,
        'bp': '2972 °C', 'mp': '1843 °C', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '4.23 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<0.01 mmHg at 20°C',
        'ghs_us_h': ['H351'], 'ghs_eu_h': ['H351'], 'signal': 'Warning',
        'p_codes': ['P201', 'P202', 'P260', 'P264', 'P270', 'P280', 'P308+P313', 'P405', 'P501'],
        'osha_pel': '15 mg/m³ TWA (total); 5 mg/m³ (respirable)',
        'niosh_rel': '2.4 mg/m³ TWA (fine particle); 0.3 mg/m³ (ultrafine)',
        'niosh_idlh': '5000 mg/m³', 'acgih_tlv': '10 mg/m³ TWA (total); 3 mg/m³ (respirable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '1333-86-4', 'name': 'Carbon black',
        'synonyms': ['Lamp black', 'Furnace black', 'Channel black', 'CI Pigment Black 7'],
        'formula': 'C', 'mw': 12.01,
        'bp': '4827 °C (sublimes)', 'mp': '3550 °C', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '1.8 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': ['H351'], 'ghs_eu_h': ['H351'], 'signal': 'Warning',
        'p_codes': ['P201', 'P202', 'P260', 'P264', 'P280', 'P308+P313', 'P405', 'P501'],
        'osha_pel': '3.5 mg/m³ TWA', 'niosh_rel': '0.1 mg/m³ TWA (potential carcinogen)',
        'niosh_idlh': '1750 mg/m³', 'acgih_tlv': '3 mg/m³ TWA (inhalable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '1314-13-2', 'name': 'Zinc oxide',
        'synonyms': ['ZnO', 'Zinc white', 'CI Pigment White 4', 'Flowers of zinc'],
        'formula': 'ZnO', 'mw': 81.38,
        'bp': '1975 °C', 'mp': '1975 °C', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '5.6 g/cm³',
        'solubility': '1.6 mg/L at 29°C', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': ['H400', 'H410'], 'ghs_eu_h': ['H400', 'H410'], 'signal': 'Warning',
        'p_codes': ['P260', 'P264', 'P270', 'P273', 'P391', 'P501'],
        'osha_pel': '5 mg/m³ TWA (fume); 15 mg/m³ TWA (dust)',
        'niosh_rel': '5 mg/m³ TWA; 15 mg/m³ STEL (fume)',
        'niosh_idlh': '500 mg/m³', 'acgih_tlv': '2 mg/m³ TWA (respirable, fume)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '1309-37-1', 'name': 'Iron oxide, red',
        'synonyms': ['Ferric oxide', 'Iron(III) oxide', 'CI Pigment Red 101', 'Fe2O3'],
        'formula': 'Fe2O3', 'mw': 159.69,
        'bp': '1565 °C', 'mp': '1565 °C', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '5.24 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': [], 'ghs_eu_h': [], 'signal': None, 'p_codes': [],
        'osha_pel': '10 mg/m³ TWA (dust); 5 mg/m³ (fume)',
        'niosh_rel': '5 mg/m³ TWA (dust and fume)',
        'niosh_idlh': '2500 mg/m³', 'acgih_tlv': '5 mg/m³ TWA (respirable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '51274-00-1', 'name': 'Iron oxide, yellow',
        'synonyms': ['Ferric oxide yellow', 'CI Pigment Yellow 42', 'Iron(III) oxide monohydrate'],
        'formula': 'FeOOH', 'mw': 88.85,
        'bp': '150 °C (decomposes)', 'mp': '150 °C (decomposes)', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '4.0 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': [], 'ghs_eu_h': [], 'signal': None, 'p_codes': [],
        'osha_pel': '10 mg/m³ TWA (dust)', 'niosh_rel': '5 mg/m³ TWA',
        'niosh_idlh': '2500 mg/m³', 'acgih_tlv': '5 mg/m³ TWA (respirable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    # ── Extenders & Fillers ───────────────────────────────────────────────────
    {
        'cas': '1317-65-3', 'name': 'Calcium carbonate',
        'synonyms': ['Limestone', 'Calcite', 'Chalk', 'Whiting', 'CaCO3'],
        'formula': 'CaCO3', 'mw': 100.09,
        'bp': '825 °C (decomposes)', 'mp': '1339 °C', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '2.71 g/cm³',
        'solubility': '0.013 g/L at 25°C', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': [], 'ghs_eu_h': [], 'signal': None, 'p_codes': [],
        'osha_pel': '15 mg/m³ TWA (total); 5 mg/m³ (respirable)',
        'niosh_rel': '10 mg/m³ TWA (total); 5 mg/m³ (respirable)',
        'niosh_idlh': 'Not determined', 'acgih_tlv': '10 mg/m³ TWA (inhalable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '7727-43-7', 'name': 'Barium sulfate',
        'synonyms': ['Barite', 'Blanc fixe', 'BaSO4', 'CI Pigment White 22'],
        'formula': 'BaSO4', 'mw': 233.39,
        'bp': '1600 °C (decomposes)', 'mp': '1580 °C', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '4.48 g/cm³',
        'solubility': '0.00024 g/L at 20°C', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': [], 'ghs_eu_h': [], 'signal': None, 'p_codes': [],
        'osha_pel': '15 mg/m³ TWA (total); 5 mg/m³ (respirable)',
        'niosh_rel': '10 mg/m³ TWA (total); 5 mg/m³ (respirable)',
        'niosh_idlh': 'Not determined', 'acgih_tlv': '10 mg/m³ TWA (inhalable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '14807-96-6', 'name': 'Talc',
        'synonyms': ['Magnesium silicate', 'Talcum', 'French chalk'],
        'formula': 'H2Mg3(SiO3)4', 'mw': 379.27,
        'bp': 'N/A', 'mp': 'N/A', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '2.7 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': ['H351'], 'ghs_eu_h': ['H351'], 'signal': 'Warning',
        'p_codes': ['P201', 'P202', 'P260', 'P280', 'P308+P313', 'P405', 'P501'],
        'osha_pel': '20 mppcf TWA (< 1% crystalline silica)',
        'niosh_rel': '2 mg/m³ TWA (respirable, asbestos-free)',
        'niosh_idlh': '1000 mg/m³', 'acgih_tlv': '2 mg/m³ TWA (respirable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '1332-58-7', 'name': 'Kaolin',
        'synonyms': ['Kaolin clay', 'China clay', 'Aluminum silicate', 'Kaolinite'],
        'formula': 'Al2O3·2SiO2·2H2O', 'mw': 258.16,
        'bp': 'N/A', 'mp': 'N/A', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '2.6 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': [], 'ghs_eu_h': [], 'signal': None, 'p_codes': [],
        'osha_pel': '15 mg/m³ TWA (total); 5 mg/m³ (respirable)',
        'niosh_rel': '10 mg/m³ TWA (total); 5 mg/m³ (respirable)',
        'niosh_idlh': 'Not determined', 'acgih_tlv': '2 mg/m³ TWA (respirable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '7631-86-9', 'name': 'Silicon dioxide, amorphous',
        'synonyms': ['Amorphous silica', 'Fumed silica', 'Precipitated silica', 'SiO2'],
        'formula': 'SiO2', 'mw': 60.08,
        'bp': '2230 °C', 'mp': '1600 °C', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '2.2 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': ['H335'], 'ghs_eu_h': ['H335'], 'signal': 'Warning',
        'p_codes': ['P261', 'P271', 'P304+P340', 'P312', 'P501'],
        'osha_pel': '6 mg/m³ TWA (amorphous)',
        'niosh_rel': '6 mg/m³ TWA (amorphous)',
        'niosh_idlh': '3000 mg/m³', 'acgih_tlv': '10 mg/m³ TWA (inhalable, amorphous)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    # ── Additives & Misc ──────────────────────────────────────────────────────
    {
        'cas': '7732-18-5', 'name': 'Water',
        'synonyms': ['Deionized water', 'Distilled water', 'H2O'],
        'formula': 'H2O', 'mw': 18.02,
        'bp': '100 °C', 'mp': '0 °C', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '1.0 g/cm³',
        'solubility': 'N/A', 'vapor_pressure': '23 mmHg at 20°C',
        'ghs_us_h': [], 'ghs_eu_h': [], 'signal': None, 'p_codes': [],
        'osha_pel': 'Not established', 'niosh_rel': 'Not established',
        'niosh_idlh': 'Not determined', 'acgih_tlv': 'Not established',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '1336-21-6', 'name': 'Ammonia solution',
        'synonyms': ['Ammonium hydroxide', 'Aqueous ammonia', 'Ammonia water'],
        'formula': 'NH4OH', 'mw': 35.05,
        'bp': '38 °C (10-15% solution)', 'mp': None, 'fp': 'Non-flammable (solution)',
        'auto_ign': None, 'density': '0.91 g/cm³ (28%)',
        'solubility': 'Miscible with water', 'vapor_pressure': '11 mmHg at 20°C (as NH3)',
        'ghs_us_h': ['H290', 'H314', 'H335', 'H400'],
        'ghs_eu_h': ['H290', 'H314', 'H335', 'H400'], 'signal': 'Danger',
        'p_codes': ['P234', 'P260', 'P264', 'P271', 'P273', 'P280',
                    'P301+P330+P331', 'P303+P361+P353', 'P304+P340', 'P305+P351+P338',
                    'P310', 'P321', 'P363', 'P390', 'P391', 'P405', 'P501'],
        'osha_pel': '50 ppm (35 mg/m³) TWA',
        'niosh_rel': '25 ppm (18 mg/m³) TWA; 35 ppm STEL',
        'niosh_idlh': '300 ppm', 'acgih_tlv': '25 ppm TWA; 35 ppm STEL',
        'un': 'UN2672', 'dot_class': '8', 'dot_pg': 'III',
        'dot_labels': 'Corrosive', 'marine': False,
    },
    {
        'cas': '7779-90-0', 'name': 'Zinc phosphate',
        'synonyms': ['Trizinc bis(orthophosphate)', 'Zinc orthophosphate'],
        'formula': 'Zn3(PO4)2', 'mw': 386.11,
        'bp': 'N/A', 'mp': '900 °C (decomposes)', 'fp': 'Non-flammable',
        'auto_ign': None, 'density': '3.998 g/cm³',
        'solubility': '0.0001 g/L at 20°C', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': ['H400', 'H410'], 'ghs_eu_h': ['H400', 'H410'], 'signal': 'Warning',
        'p_codes': ['P260', 'P264', 'P270', 'P273', 'P391', 'P501'],
        'osha_pel': '15 mg/m³ TWA (total dust)', 'niosh_rel': '10 mg/m³ TWA',
        'niosh_idlh': 'Not determined', 'acgih_tlv': '10 mg/m³ TWA (inhalable)',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
    {
        'cas': '100-42-5', 'name': 'Styrene',
        'synonyms': ['Vinylbenzene', 'Ethenylbenzene', 'Styrene monomer', 'Phenylethylene'],
        'formula': 'C8H8', 'mw': 104.15,
        'bp': '145 °C (293 °F)', 'mp': '-31 °C', 'fp': '34 °C (93 °F)',
        'auto_ign': '490 °C', 'density': '0.906 g/cm³',
        'solubility': '300 mg/L at 25°C', 'vapor_pressure': '5 mmHg at 20°C',
        'ghs_us_h': ['H226', 'H315', 'H319', 'H332', 'H350'],
        'ghs_eu_h': ['H226', 'H315', 'H319', 'H332', 'H350'], 'signal': 'Danger',
        'p_codes': ['P201', 'P202', 'P210', 'P260', 'P264', 'P271', 'P280',
                    'P301+P312', 'P302+P352', 'P304+P340', 'P305+P351+P338', 'P308+P313',
                    'P337+P313', 'P370+P378', 'P403+P235', 'P405', 'P501'],
        'osha_pel': '100 ppm (420 mg/m³) TWA; 200 ppm ceiling',
        'niosh_rel': '50 ppm (215 mg/m³) TWA; 100 ppm STEL',
        'niosh_idlh': '700 ppm', 'acgih_tlv': '20 ppm TWA; 40 ppm STEL',
        'un': 'UN2055', 'dot_class': '3', 'dot_pg': 'III',
        'dot_labels': 'Flammable Liquid', 'marine': False,
    },
    {
        'cas': '8001-26-1', 'name': 'Linseed oil',
        'synonyms': ['Flaxseed oil', 'Linum usitatissimum seed oil'],
        'formula': '', 'mw': None,
        'bp': '>300 °C', 'mp': '-24 °C', 'fp': '222 °C (432 °F)',
        'auto_ign': None, 'density': '0.93 g/cm³',
        'solubility': 'Insoluble in water', 'vapor_pressure': '<0.01 mmHg',
        'ghs_us_h': [], 'ghs_eu_h': [], 'signal': None, 'p_codes': [],
        'osha_pel': 'Not established', 'niosh_rel': 'Not established',
        'niosh_idlh': 'Not determined', 'acgih_tlv': 'Not established',
        'un': None, 'dot_class': None, 'dot_pg': None, 'dot_labels': None, 'marine': False,
    },
]


def load(db_path):
    """Load bundled chemical data into the master database."""
    conn = sqlite3.connect(db_path)
    conn.execute('PRAGMA journal_mode=WAL')
    now = datetime.now(timezone.utc).isoformat()

    loaded = 0
    for chem in CHEMICALS:
        cas = chem['cas']
        conn.execute('''
            INSERT INTO chemicals
                (cas_number, common_name, molecular_formula, molecular_weight,
                 boiling_point, melting_point, flash_point, auto_ignition,
                 density, solubility, vapor_pressure,
                 ghs_us_h_codes, ghs_us_signal,
                 ghs_eu_h_codes, ghs_eu_signal,
                 p_codes,
                 osha_pel, niosh_rel, niosh_idlh, acgih_tlv,
                 un_number, dot_hazard_class, dot_packing_group, dot_labels,
                 marine_pollutant,
                 data_sources, last_updated)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(cas_number) DO UPDATE SET
                common_name     = excluded.common_name,
                molecular_formula = excluded.molecular_formula,
                molecular_weight  = excluded.molecular_weight,
                boiling_point   = COALESCE(excluded.boiling_point,  boiling_point),
                melting_point   = COALESCE(excluded.melting_point,  melting_point),
                flash_point     = COALESCE(excluded.flash_point,    flash_point),
                auto_ignition   = COALESCE(excluded.auto_ignition,  auto_ignition),
                density         = COALESCE(excluded.density,        density),
                solubility      = COALESCE(excluded.solubility,     solubility),
                vapor_pressure  = COALESCE(excluded.vapor_pressure, vapor_pressure),
                ghs_us_h_codes  = excluded.ghs_us_h_codes,
                ghs_us_signal   = excluded.ghs_us_signal,
                ghs_eu_h_codes  = excluded.ghs_eu_h_codes,
                ghs_eu_signal   = excluded.ghs_eu_signal,
                p_codes         = excluded.p_codes,
                osha_pel        = COALESCE(excluded.osha_pel,  osha_pel),
                niosh_rel       = COALESCE(excluded.niosh_rel, niosh_rel),
                niosh_idlh      = COALESCE(excluded.niosh_idlh, niosh_idlh),
                acgih_tlv       = COALESCE(excluded.acgih_tlv, acgih_tlv),
                un_number       = COALESCE(excluded.un_number, un_number),
                dot_hazard_class  = COALESCE(excluded.dot_hazard_class, dot_hazard_class),
                dot_packing_group = COALESCE(excluded.dot_packing_group, dot_packing_group),
                dot_labels        = COALESCE(excluded.dot_labels, dot_labels),
                marine_pollutant  = MAX(marine_pollutant, excluded.marine_pollutant),
                data_sources    = excluded.data_sources,
                last_updated    = excluded.last_updated
        ''', (
            cas,
            chem['name'],
            chem.get('formula') or None,
            chem.get('mw'),
            chem.get('bp') or None,
            chem.get('mp') or None,
            chem.get('fp') or None,
            chem.get('auto_ign') or None,
            chem.get('density') or None,
            chem.get('solubility') or None,
            chem.get('vapor_pressure') or None,
            json.dumps(chem.get('ghs_us_h', [])),
            chem.get('signal'),
            json.dumps(chem.get('ghs_eu_h', [])),
            chem.get('signal'),
            json.dumps(chem.get('p_codes', [])),
            chem.get('osha_pel') or None,
            chem.get('niosh_rel') or None,
            chem.get('niosh_idlh') or None,
            chem.get('acgih_tlv') or None,
            chem.get('un'),
            chem.get('dot_class'),
            chem.get('dot_pg'),
            chem.get('dot_labels'),
            1 if chem.get('marine') else 0,
            json.dumps(['Bundled — NIOSH NPG / OSHA / ECHA / DOT 49 CFR']),
            now,
        ))

        # Synonyms
        all_names = [chem['name']] + chem.get('synonyms', [])
        for name in all_names:
            if name:
                conn.execute('''
                    INSERT OR IGNORE INTO chemical_synonyms (cas_number, name, source)
                    VALUES (?, ?, 'Bundled')
                ''', (cas, name[:512]))

        loaded += 1

    conn.execute(
        'INSERT INTO import_log (source, filename, rows_loaded) VALUES (?,?,?)',
        ('Bundled paint chemicals', 'bundled_parser.py', loaded)
    )
    conn.commit()
    conn.close()
    print(f"Bundled: loaded {loaded} common paint/coating chemicals")
    return loaded
